# Builds the site and deploys it.
name: Build and Deploy

# Triggers the workflow on push for the master branch
on:
  push:
    branches: [master]

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: setup
        run: yarn install
        working-directory: server

      - name: build
        run: yarn run prod
        working-directory: server

      - name: verify built output
        run: find server/dist/ -print
